### ISSUE TITLE
Build is throwing error.

### ISSUE THREAD

**Issue by josedesignr** [nosoycesaros/react-quickstart#6]
Thanks a lot guys for this project, it was really useful for me.

But I got these errors when I tried to build:

ERROR in   TypeError: Cannot use 'in' operator to search for 'html5' in true
  
  - htmlminifier.js:610 
    [strv]/[html-minifier]/src/htmlminifier.js:610:18
  
  - Array.forEach
  
  - htmlminifier.js:609 processOptions
    [strv]/[html-minifier]/src/htmlminifier.js:609:41
  
  - htmlminifier.js:819 minify
    [strv]/[html-minifier]/src/htmlminifier.js:819:3
  
  - htmlminifier.js:1294 exports.minify
    [strv]/[html-minifier]/src/htmlminifier.js:1294:10
  
  - index.js:287 
    [strv]/[html-webpack-plugin]/index.js:287:16
  
  - util.js:16 tryCatcher
    [strv]/[html-webpack-plugin]/[bluebird]/js/release/util.js:16:23
  
  - promise.js:504 Promise._settlePromiseFromHandler
    [strv]/[html-webpack-plugin]/[bluebird]/js/release/promise.js:504:31
  
  - promise.js:561 Promise._settlePromise
    [strv]/[html-webpack-plugin]/[bluebird]/js/release/promise.js:561:18
  
  - promise.js:606 Promise._settlePromise0
    [strv]/[html-webpack-plugin]/[bluebird]/js/release/promise.js:606:10
  
  - promise.js:685 Promise._settlePromises
    [strv]/[html-webpack-plugin]/[bluebird]/js/release/promise.js:685:18
  
  - async.js:138 Async._drainQueue
    [strv]/[html-webpack-plugin]/[bluebird]/js/release/async.js:138:16
  
  - async.js:148 Async._drainQueues
    [strv]/[html-webpack-plugin]/[bluebird]/js/release/async.js:148:10
  
  - async.js:17 Immediate.Async.drainQueues [as _onImmediate]
    [strv]/[html-webpack-plugin]/[bluebird]/js/release/async.js:17:14

**Comment by androide-osorio** [comment]
This problem happens because of the `html-webpack-plugin`, the plugin that extracts HTML modules from the project into a single index file and injects the generated bundles into it. There was a recent modification to this plugin, specifically for the `minify` option, where it expects its value to be either a valid [html-minifier](https://github.com/kangax/html-minifier) configuration, or `false` to disable minification.

In the quickstart, we're passing `true` as the value. This was a valid value before in the plugin, but now it is not (because `true` is not an object.

Thanks for reporting this 😄
