### ISSUE TITLE
Cannot use "background-image" property in scss file.

### ISSUE THREAD

**Issue by josedesignr** [nosoycesaros/react-quickstart#7]
Hi folks!

I have discovered that if I use "background-image" property via scss, it does not compile. Throws an error, so I had to remove all the background-image properties along the scss file and pass the urls via javascript.

**Comment by androide-osorio** [comment]
@josedesignr I was able to reproduce the bug you just reported. Can you confirm that the screenshot below is indeed what happens??
![sass background image issue: ModuleNotFoundError: Module not found: Error: Cannot resolve module 'file'](https://dl.dropboxusercontent.com/u/20749637/images/github/react-quickstart/issue7-error-confirmation.png)

The error I was able to reproduce said that the module 'file' for webpack was not found. I found out that this happens because the `file-loader` package for webpack is not being included. When the `sass-loader` finds `url()` statements in the SASS files, it will try to resolve them using the file loader.

@nosoycesaros can you take care of this??

**Comment by josedesignr** [comment]
Hi again guys,

It is recognizing images referenced in SCSS, but only in development.
If I run the build script, the building does not result as expected.

Perhaps it is my mistake, but can you check please that it is not a bug in the QuickStart project?

Thanks!
